<?php
ob_start();
session_start();

require('../fpdf/fpdf.php');
include '../includes/db.php';

if(!isset($_SESSION['user_id'])){
    die("Login required");
}

$user_id = $_SESSION['user_id'];

$result = $conn->query("
    SELECT date_added, status 
    FROM attendance 
    WHERE student_id='$user_id'
    ORDER BY date_added DESC
");

/* SUMMARY */
$present = $conn->query("SELECT COUNT(*) as total FROM attendance WHERE student_id='$user_id' AND status='present'")->fetch_assoc()['total'];
$absent  = $conn->query("SELECT COUNT(*) as total FROM attendance WHERE student_id='$user_id' AND status='absent'")->fetch_assoc()['total'];

$total = $present + $absent;
$rate = $total > 0 ? round(($present/$total)*100) : 0;

class PDF extends FPDF {
    function Footer(){
        $this->SetY(-15);
        $this->SetFont('Arial','I',9);
        $this->Cell(0,10,'Generated by School Attendance System | '.date("M d, Y"),0,0,'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();

$pdf->SetFont('Arial','B',18);
$pdf->SetTextColor(40,40,40);
$pdf->Cell(0,10,'SCHOOL ATTENDANCE REPORT',0,1,'C');

$pdf->Ln(3);

$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Student ID: '.$user_id,0,1);
$pdf->Cell(0,8,'Date Generated: '.date("M d, Y h:i A"),0,1);

$pdf->Ln(5);

$pdf->SetFont('Arial','B',12);

$pdf->SetFillColor(220, 252, 231); // green light
$pdf->Cell(60,10,"Present: $present",1,0,'C',true);

$pdf->SetFillColor(254, 226, 226); // red light
$pdf->Cell(60,10,"Absent: $absent",1,0,'C',true);

$pdf->SetFillColor(219, 234, 254); // blue light
$pdf->Cell(60,10,"Rate: $rate%",1,1,'C',true);

$pdf->Ln(8);

$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(59,130,246); // blue
$pdf->SetTextColor(255);

$pdf->Cell(95,10,'Date',1,0,'C',true);
$pdf->Cell(95,10,'Status',1,1,'C',true);

$pdf->SetFont('Arial','',11);
$pdf->SetTextColor(0);

if($result->num_rows > 0){

    while($row = $result->fetch_assoc()){

        $date = date('M d, Y - h:i A', strtotime($row['date_added']));
        $status = ucfirst($row['status']);

        // COLOR STATUS
        if($status == "Present"){
            $pdf->SetTextColor(22,163,74); // green
        } else {
            $pdf->SetTextColor(220,38,38); // red
        }

        $pdf->Cell(95,10,$date,1,0,'C');
        $pdf->Cell(95,10,$status,1,1,'C');
    }

}else{
    $pdf->SetTextColor(0);
    $pdf->Cell(190,10,'No attendance records found',1,1,'C');
}


$pdf->Output('I','Attendance_Report.pdf');
ob_end_flush();